### ISSUE TITLE
requestLiveGameForUser callback not being executed

### ISSUE THREAD

**Issue by EloB** [joshuaferrara/node-csgo#61]
https://github.com/joshuaferrara/node-csgo/blob/master/handlers/match.js#L39

I'm able to get the event, `matchList`, to trigger but not that callback. I rather use that callback because it fits my needs better. Can this be fixed?

**Comment by EloB** [comment]
Anyone? I'm having problem with that event because I don't get that error. I really want to use that `callback`.

**Comment by joshuaferrara** [comment]
Hi,

The callback argument on the line you linked to does not work (it should not be there). The documentation has the appropriate function signatures that should be used for development. 

In general, no callbacks are available within node-csgo. They could be implemented, although it tends to be a bit hacky (run a callback once we've received an event with the proper steam ID, or other key-like parameter to identify the proper response). In some cases this would work, in others it wouldn't; due to this, it was never implemented and is left as something for the caller to resolve. 

For anyone interested, a PR for callback functionality is welcomed.
