### ISSUE TITLE
can`t get ranking info with playerProfileRequest()

### ISSUE THREAD

**Issue by filoret256** [joshuaferrara/node-csgo#8]
can`t get ranking info with playerProfileRequest()
recieve all info except ranking

**Comment by joshuaferrara** [comment]
I'll see what I can do about fixing this. Probably a protobuf change but that's unlikely.

**Comment by joshuaferrara** [comment]
I'm currently not able to replicate this issue or do really any testing on this - my account lost it's MM rank due to inactivity. If someone else would like to pitch in some info, that would be great.

**Comment by switz** [comment]
I definitely used it quite a bit today. It works.

**Comment by joshuaferrara** [comment]
Thanks for the input @switz 

Sounds like it might have just been an issue on @filoret256  end then or it's due to no rank available. When I tested, I got an empty object back but keep in mind I do not have a rank. I'm going to close this issue but if it arises again, feel free to reopen it @filoret256
